import { expect, test } from "@playwright/test";

test("anonymous navigation stays restrained and guest tracking is accessible", async ({ page }) => {
  await page.goto("/");
  const primary = page.getByRole("navigation", { name: "Primary navigation" });
  await expect(primary.getByRole("link")).toHaveCount(2);
  await expect(page.getByRole("link", { name: "Sign in", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Account options" })).toHaveCount(0);
  await expect(page.getByRole("navigation", { name: "Footer navigation" }).getByRole("link")).toHaveCount(3);
  await page.setViewportSize({ width: 320, height: 720 });
  await page.getByRole("button", { name: "Open customer navigation" }).click();
  const dialog = page.getByRole("dialog", { name: "Customer navigation" });
  await expect(dialog.getByRole("link", { name: "Sign in" })).toBeVisible();
  await dialog.getByRole("link", { name: "Track order" }).click();
  await expect(page).toHaveURL(/\/track-order$/);
  await expect(dialog).not.toBeVisible();
  await page.goto("/login");
  await expect(page.getByRole("button", { name: "Continue with Google" })).toBeVisible();
  const artwork = page.locator('img[src*="google-sign-in-light"]');
  await expect(artwork).toBeVisible();
  await artwork.scrollIntoViewIfNeeded();
  await expect.poll(() => artwork.evaluate((node) => (node as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  const bounds = await artwork.boundingBox();
  expect(bounds!.width / bounds!.height).toBeCloseTo(4.5, 1);
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: "instant" }));
  await page.screenshot({ path: test.info().outputPath("mobile-google-entry.png"), fullPage: true, animations: "disabled" });
});

test("account disclosure and sections preserve focus, drafts, responsive layout and logout recovery", async ({ page }) => {
  await page.goto("/register");
  await page.getByLabel("Name").fill("Navigation Customer");
  await page.getByLabel("Email").fill("stage153.navigation@example.test");
  await page.getByLabel("Password", { exact: true }).fill("Navigation browser password 123!");
  await page.getByLabel("Confirm password").fill("Navigation browser password 123!");
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page).toHaveURL(/\/account$/);
  const trigger = page.getByRole("button", { name: "Account options" });
  await expect(page.getByRole("button", { name: "Sign out" })).toHaveCount(0);
  await trigger.focus(); await page.keyboard.press("ArrowDown");
  await expect(page.getByRole("link", { name: "Account", exact: true })).toBeFocused();
  await page.keyboard.press("End");
  await expect(page.getByRole("button", { name: "Sign out" })).toBeFocused();
  await page.keyboard.press("Tab");
  await expect(page.getByRole("button", { name: "Open cart" })).toBeFocused();
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  await trigger.click();
  await expect(trigger).toHaveAttribute("aria-expanded", "true");
  await page.keyboard.press("Escape"); await expect(trigger).toBeFocused();
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  await trigger.click();
  await expect(trigger).toHaveAttribute("aria-expanded", "true");
  await page.locator(".customer-disclosure").evaluate(async (node) => {
    await new Promise<void>((resolve) => requestAnimationFrame(() => resolve()));
    await Promise.all(node.getAnimations().map((animation) => animation.finished));
  });
  await page.screenshot({ path: test.info().outputPath("desktop-account-dropdown.png"), fullPage: true });
  await page.getByRole("heading", { name: "Account", exact: true }).click();
  await expect(trigger).toHaveAttribute("aria-expanded", "false");
  const sections = page.getByRole("navigation", { name: "Account sections" });
  await page.getByLabel("Name").fill("Unsaved Navigation Customer");
  await sections.getByRole("link", { name: "Sign-in & Security" }).click();
  await expect(page).toHaveURL(/#security$/);
  await expect(page.getByRole("heading", { name: "Sign-in & Security" })).toBeFocused();
  await expect(sections.getByRole("link", { name: "Sign-in & Security" })).toHaveAttribute("aria-current", "location");
  await expect(page.getByLabel("Current password", { exact: true })).not.toBeVisible();
  await page.locator("summary").filter({ hasText: "Change password" }).click();
  await expect(page.getByLabel("Current password", { exact: true })).toBeVisible();
  await sections.getByRole("link", { name: "Profile" }).click();
  await expect(page.getByRole("heading", { name: "Profile" })).toBeFocused();
  await expect(page.getByLabel("Name")).toHaveValue("Unsaved Navigation Customer");
  await page.goBack();
  await expect(page.getByRole("heading", { name: "Sign-in & Security" })).toBeFocused();
  await expect(sections.getByRole("link", { name: "Sign-in & Security" })).toHaveAttribute("aria-current", "location");
  await page.goForward();
  await expect(page.getByRole("heading", { name: "Profile" })).toBeFocused();
  await sections.getByRole("link", { name: "Orders", exact: true }).click();
  await expect(page).toHaveURL(/\/account\/orders$/);
  await expect(sections.getByRole("link", { name: "Orders" })).toHaveAttribute("aria-current", "location");
  await sections.getByRole("link", { name: "Profile" }).click();
  await expect(page.getByRole("heading", { name: "Profile" })).toBeFocused();
  for (const width of [1440, 1024, 820, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth - innerWidth)).toBeLessThanOrEqual(1);
  }
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: "instant" }));
  await page.screenshot({ path: test.info().outputPath("mobile-account.png"), fullPage: true, animations: "disabled" });
  const mobileTrigger = page.getByRole("button", { name: "Open customer navigation" });
  await mobileTrigger.click();
  const mobile = page.getByRole("dialog", { name: "Customer navigation" });
  await expect(mobile.getByRole("link", { name: "Track order" })).toBeVisible();
  await expect(mobile.getByRole("link", { name: "Orders" })).toBeVisible();
  await mobile.getByRole("link", { name: "Sign-in & Security" }).click();
  await expect(page.getByRole("heading", { name: "Sign-in & Security" })).toBeFocused();
  await mobileTrigger.click(); await page.keyboard.press("Escape"); await expect(mobileTrigger).toBeFocused();
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.route("**/api/customer/auth/logout", async (route) => {
    await new Promise((resolve) => setTimeout(resolve, 300));
    await route.fulfill({ status: 503, body: "Unavailable" });
  });
  await trigger.click(); await page.getByRole("button", { name: "Sign out" }).click();
  expect(await page.locator(".customer-disclosure").evaluate((node) => getComputedStyle(node).animationName)).toBe("none");
  await expect(page.locator(".customer-disclosure").getByRole("alert")).toContainText("We couldn’t reach your account");
  await expect(trigger).toHaveAttribute("aria-expanded", "true");
  await page.unroute("**/api/customer/auth/logout");
  await page.getByRole("button", { name: "Sign out" }).click();
  await expect(page.getByRole("link", { name: "Sign in", exact: true })).toBeVisible();
});
